[package]
name = "block-multiplier-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
block-multiplier = { path = "../block-multiplier" }
hla = { path = "../hla" }
montgomery_reduction = { path = "../experiments" }
